### ISSUE TITLE
build_kernel.sh file is missing

### ISSUE THREAD

**Issue by pythonfansx** [ravindu644/android_kernel_apatch_beyondx#47]
As a beginner in Android development, I tried to compile this project. However, during the compilation process, I noticed that the build_kernel.sh file is missing. Could you please guide me on how to properly compile this project?

**Comment by ravindu644** [comment]
> As a beginner in Android development, I tried to compile this project. However, during the compilation process, I noticed that the build_kernel.sh file is missing. Could you please guide me on how to properly compile this project?

1. I renamed the `build_kernel.sh` to `build.sh` and you can find it in the root of the source's directory.
2.  If you are a beginner, I would not recommend this kernel to compile, because the build script is messed up and not even I can understand it anymore. So, I'd recommend this source instead, because it has more simpler build script : https://github.com/ravindu644/beyondx_stock

**Comment by pythonfansx** [comment]
> > As a beginner in Android development, I tried to compile this project. However, during the compilation process, I noticed that the build_kernel.sh file is missing. Could you please guide me on how to properly compile this project?
> 
> 1. I renamed the `build_kernel.sh` to `build.sh` and you can find it in the root of the source's directory.
> 2. If you are a beginner, I would not recommend this kernel to compile, because the build script is messed up and not even I can understand it anymore. So, I'd recommend this source instead, because it has more simpler build script : https://github.com/ravindu644/beyondx_stock

thanks .
